#ifndef BUILTINS_IPHLPAPI_H
#define BUILTINS_IPHLPAPI_H

IPHLPAPI$GetNumberOfInterfaces: u32 (ptr);
IPHLPAPI$GetIfEntry: u32 (ptr);
IPHLPAPI$GetIfTable: u32 (ptr, ptr, u32);
IPHLPAPI$GetIpAddrTable: u32 (ptr, ptr, u32);
IPHLPAPI$GetIpNetTable: u32 (ptr, ptr, u32);
IPHLPAPI$GetIpForwardTable: u32 (ptr, ptr, u32);
IPHLPAPI$GetTcpTable: u32 (ptr, ptr, u32);
IPHLPAPI$GetExtendedTcpTable: u32 (ptr, ptr, u32, u32, u32, u32);
IPHLPAPI$GetOwnerModuleFromTcpEntry: u32 (ptr, u32, ptr, ptr);
IPHLPAPI$GetUdpTable: u32 (ptr, ptr, u32);
IPHLPAPI$GetExtendedUdpTable: u32 (ptr, ptr, u32, u32, u32, u32);
IPHLPAPI$GetOwnerModuleFromUdpEntry: u32 (ptr, u32, ptr, ptr);
IPHLPAPI$GetTcpTable2: u32 (ptr, ptr, u32);
IPHLPAPI$GetTcp6Table: u32 (ptr, ptr, u32);
IPHLPAPI$GetTcp6Table2: u32 (ptr, ptr, u32);
IPHLPAPI$GetPerTcpConnectionEStats: u32 (ptr, u32, ptr, u32, u32, ptr, u32, u32, ptr, u32, u32);
IPHLPAPI$SetPerTcpConnectionEStats: u32 (ptr, u32, ptr, u32, u32, u32);
IPHLPAPI$GetPerTcp6ConnectionEStats: u32 (ptr, u32, ptr, u32, u32, ptr, u32, u32, ptr, u32, u32);
IPHLPAPI$SetPerTcp6ConnectionEStats: u32 (ptr, u32, ptr, u32, u32, u32);
IPHLPAPI$GetUdp6Table: u32 (ptr, ptr, u32);
IPHLPAPI$GetOwnerModuleFromTcp6Entry: u32 (ptr, u32, ptr, ptr);
IPHLPAPI$GetOwnerModuleFromUdp6Entry: u32 (ptr, u32, ptr, ptr);
IPHLPAPI$GetIpStatistics: u32 (ptr);
IPHLPAPI$GetIcmpStatistics: u32 (ptr);
IPHLPAPI$GetTcpStatistics: u32 (ptr);
IPHLPAPI$GetUdpStatistics: u32 (ptr);
IPHLPAPI$GetIpStatisticsEx: u32 (ptr, u32);
IPHLPAPI$SetIpStatisticsEx: u32 (ptr, u32);
IPHLPAPI$GetIcmpStatisticsEx: u32 (ptr, u32);
IPHLPAPI$GetTcpStatisticsEx: u32 (ptr, u32);
IPHLPAPI$GetUdpStatisticsEx: u32 (ptr, u32);
IPHLPAPI$SetIfEntry: u32 (ptr);
IPHLPAPI$CreateIpForwardEntry: u32 (ptr);
IPHLPAPI$SetIpForwardEntry: u32 (ptr);
IPHLPAPI$DeleteIpForwardEntry: u32 (ptr);
IPHLPAPI$SetIpStatistics: u32 (ptr);
IPHLPAPI$SetIpTTL: u32 (u32);
IPHLPAPI$CreateIpNetEntry: u32 (ptr);
IPHLPAPI$SetIpNetEntry: u32 (ptr);
IPHLPAPI$DeleteIpNetEntry: u32 (ptr);
IPHLPAPI$FlushIpNetTable: u32 (u32);
IPHLPAPI$CreateProxyArpEntry: u32 (u32, u32, u32);
IPHLPAPI$DeleteProxyArpEntry: u32 (u32, u32, u32);
IPHLPAPI$SetTcpEntry: u32 (ptr);
IPHLPAPI$GetInterfaceInfo: u32 (ptr, ptr);
IPHLPAPI$GetUniDirectionalAdapterInfo: u32 (ptr, ptr);
IPHLPAPI$NhpAllocateAndGetInterfaceInfoFromStack: u32 (ptr, ptr, u32, ptr, u32);
IPHLPAPI$GetBestInterface: u32 (u32, ptr);
IPHLPAPI$GetBestInterfaceEx: u32 (ptr, ptr);
IPHLPAPI$GetBestRoute: u32 (u32, u32, ptr);
IPHLPAPI$NotifyAddrChange: u32 (ptr, ptr);
IPHLPAPI$NotifyRouteChange: u32 (ptr, ptr);
IPHLPAPI$CancelIPChangeNotify: u32 (ptr);
IPHLPAPI$GetAdapterIndex: u32 (ptr, ptr);
IPHLPAPI$AddIPAddress: u32 (u32, u32, u32, ptr, ptr);
IPHLPAPI$DeleteIPAddress: u32 (u32);
IPHLPAPI$GetNetworkParams: u32 (ptr, ptr);
IPHLPAPI$GetAdaptersInfo: u32 (ptr, ptr);
IPHLPAPI$GetAdapterOrderMap: ptr ();
IPHLPAPI$GetAdaptersAddresses: u32 (u32, u32, ptr, ptr, ptr);
IPHLPAPI$GetPerAdapterInfo: u32 (u32, ptr, ptr);
IPHLPAPI$IpReleaseAddress: u32 (ptr);
IPHLPAPI$IpRenewAddress: u32 (ptr);
IPHLPAPI$SendARP: u32 (u32, u32, ptr, ptr);
IPHLPAPI$GetRTTAndHopCount: u32 (u32, ptr, u32, ptr);
IPHLPAPI$GetFriendlyIfIndex: u32 (u32);
IPHLPAPI$EnableRouter: u32 (ptr, ptr);
IPHLPAPI$UnenableRouter: u32 (ptr, ptr);
IPHLPAPI$DisableMediaSense: u32 (ptr, ptr);
IPHLPAPI$RestoreMediaSense: u32 (ptr, ptr);
IPHLPAPI$ParseNetworkString: u32 (ptr, u32, ptr, ptr, ptr);
IPHLPAPI$GetIpErrorString: u32 (u32, ptr, ptr);
IPHLPAPI$ResolveNeighbor: u32 (ptr, ptr, ptr);
IPHLPAPI$CreatePersistentTcpPortReservation: u32 (u16, u16, ptr);
IPHLPAPI$CreatePersistentUdpPortReservation: u32 (u16, u16, ptr);
IPHLPAPI$DeletePersistentTcpPortReservation: u32 (u16, u16);
IPHLPAPI$DeletePersistentUdpPortReservation: u32 (u16, u16);
IPHLPAPI$LookupPersistentTcpPortReservation: u32 (u16, u16, ptr);
IPHLPAPI$LookupPersistentUdpPortReservation: u32 (u16, u16, ptr);

#endif /* BUILTINS_IPHLPAPI_H */
