#ifndef BUILTINS_MSVCRT_H
#define BUILTINS_MSVCRT_H

MSVCRT$fprintf: cdecl i32 (ptr, cstr, ...);
MSVCRT$printf: cdecl i32 (cstr, ...);
MSVCRT$sprintf: cdecl i32 (ptr, cstr, ...);
MSVCRT$vfprintf: cdecl i32 (ptr, cstr, ptr);
MSVCRT$vprintf: cdecl i32 (cstr, ptr);
MSVCRT$vsprintf: cdecl i32 (ptr, cstr, ptr);
MSVCRT$fscanf: cdecl i32 (ptr, cstr, ...);
MSVCRT$scanf: cdecl i32 (cstr, ...);
MSVCRT$sscanf: cdecl i32 (cstr, cstr, ...);
MSVCRT$vasprintf: cdecl i32 (ptr, cstr, ptr);
MSVCRT$asprintf: cdecl i32 (ptr, cstr, ...);
MSVCRT$_filbuf: cdecl i32 (ptr);
MSVCRT$_flsbuf: cdecl i32 (i32, ptr);
MSVCRT$_fsopen: cdecl ptr (cstr, cstr, i32);
MSVCRT$clearerr: cdecl void (ptr);
MSVCRT$fclose: cdecl i32 (ptr);
MSVCRT$_fcloseall: cdecl i32 ();
MSVCRT$fdopen: cdecl ptr (i32, cstr);
MSVCRT$_fdopen: cdecl ptr (i32, cstr);
MSVCRT$feof: cdecl i32 (ptr);
MSVCRT$ferror: cdecl i32 (ptr);
MSVCRT$fflush: cdecl i32 (ptr);
MSVCRT$fgetc: cdecl i32 (ptr);
MSVCRT$_fgetchar: cdecl i32 ();
MSVCRT$fgetpos: cdecl i32 (ptr, ptr);
MSVCRT$fgetpos64: cdecl i32 (ptr, ptr);
MSVCRT$fgets: cdecl cstr (ptr, i32, ptr);
MSVCRT$_fileno: cdecl i32 (ptr);
MSVCRT$fileno: cdecl i32 (ptr);
MSVCRT$_tempnam: cdecl cstr (cstr, cstr);
MSVCRT$_flushall: cdecl i32 ();
MSVCRT$fopen: cdecl ptr (cstr, cstr);
MSVCRT$fputc: cdecl i32 (i32, ptr);
MSVCRT$_fputchar: cdecl i32 (i32);
MSVCRT$fputs: cdecl i32 (cstr, ptr);
MSVCRT$fread: cdecl size_t (ptr, size_t, size_t, ptr);
MSVCRT$freopen: cdecl ptr (cstr, cstr, ptr);
MSVCRT$fsetpos: cdecl i32 (ptr, ptr);
MSVCRT$fsetpos64: cdecl i32 (ptr, ptr);
MSVCRT$fseek: cdecl i32 (ptr, i32, i32);
MSVCRT$ftell: cdecl i32 (ptr);
MSVCRT$_fseeki64: cdecl i32 (ptr, i64, i32);
MSVCRT$_ftelli64: cdecl i64 (ptr);
MSVCRT$fwrite: cdecl size_t (ptr, size_t, size_t, ptr);
MSVCRT$getc: cdecl i32 (ptr);
MSVCRT$getchar: cdecl i32 ();
MSVCRT$_getmaxstdio: cdecl i32 ();
MSVCRT$gets: cdecl cstr (ptr);
MSVCRT$_getw: cdecl i32 (ptr);
MSVCRT$perror: cdecl void (cstr);
MSVCRT$_pclose: cdecl i32 (ptr);
MSVCRT$_popen: cdecl ptr (cstr, cstr);
MSVCRT$putc: cdecl i32 (i32, ptr);
MSVCRT$putchar: cdecl i32 (i32);
MSVCRT$puts: cdecl i32 (cstr);
MSVCRT$_putw: cdecl i32 (i32, ptr);
MSVCRT$remove: cdecl i32 (cstr);
MSVCRT$rename: cdecl i32 (cstr, cstr);
MSVCRT$_unlink: cdecl i32 (cstr);
MSVCRT$unlink: cdecl i32 (cstr);
MSVCRT$rewind: cdecl void (ptr);
MSVCRT$_rmtmp: cdecl i32 ();
MSVCRT$setbuf: cdecl void (ptr, ptr);
MSVCRT$_setmaxstdio: cdecl i32 (i32);
MSVCRT$_set_output_format: cdecl u32 (u32);
MSVCRT$_get_output_format: cdecl u32 ();
MSVCRT$setvbuf: cdecl i32 (ptr, ptr, i32, size_t);
MSVCRT$_scprintf: cdecl i32 (cstr, ...);
MSVCRT$_snscanf: cdecl i32 (cstr, size_t, cstr, ...);
MSVCRT$tmpfile: cdecl ptr ();
MSVCRT$tmpnam: cdecl cstr (ptr);
MSVCRT$ungetc: cdecl i32 (i32, ptr);
MSVCRT$_vsnprintf: cdecl i32 (ptr, size_t, cstr, ptr);
MSVCRT$_snprintf: cdecl i32 (ptr, size_t, cstr, ...);
MSVCRT$_vscprintf: cdecl i32 (cstr, ptr);
MSVCRT$_set_printf_count_output: cdecl i32 (i32);
MSVCRT$_get_printf_count_output: cdecl i32 ();
MSVCRT$fwscanf: cdecl i32 (ptr, ptr, ...);
MSVCRT$swscanf: cdecl i32 (ptr, ptr, ...);
MSVCRT$wscanf: cdecl i32 (ptr, ...);
MSVCRT$fwprintf: cdecl i32 (ptr, ptr, ...);
MSVCRT$wprintf: cdecl i32 (ptr, ...);
MSVCRT$vfwprintf: cdecl i32 (ptr, ptr, ptr);
MSVCRT$vwprintf: cdecl i32 (ptr, ptr);
MSVCRT$_wfsopen: cdecl ptr (ptr, ptr, i32);
MSVCRT$fgetwc: cdecl u32 (ptr);
MSVCRT$_fgetwchar: cdecl u32 ();
MSVCRT$fputwc: cdecl u32 (u16, ptr);
MSVCRT$_fputwchar: cdecl u32 (u16);
MSVCRT$getwc: cdecl u32 (ptr);
MSVCRT$getwchar: cdecl u32 ();
MSVCRT$putwc: cdecl u32 (u16, ptr);
MSVCRT$putwchar: cdecl u32 (u16);
MSVCRT$ungetwc: cdecl u32 (u32, ptr);
MSVCRT$fgetws: cdecl cstr (ptr, i32, ptr);
MSVCRT$fputws: cdecl i32 (ptr, ptr);
MSVCRT$_getws: cdecl cstr (ptr);
MSVCRT$_putws: cdecl i32 (ptr);
MSVCRT$_scwprintf: cdecl i32 (ptr, ...);
MSVCRT$_snwprintf: cdecl i32 (ptr, size_t, ptr, ...);
MSVCRT$_vsnwprintf: cdecl i32 (ptr, size_t, ptr, ptr);
MSVCRT$vsnwprintf: cdecl i32 (ptr, size_t, ptr, ptr);
MSVCRT$_swprintf: cdecl i32 (ptr, ptr, ...);
MSVCRT$_vswprintf: cdecl i32 (ptr, ptr, ptr);
MSVCRT$_vscwprintf: cdecl i32 (ptr, ptr);
MSVCRT$_swprintf_c: cdecl i32 (ptr, size_t, ptr, ...);
MSVCRT$_vswprintf_c: cdecl i32 (ptr, size_t, ptr, ptr);
MSVCRT$_wtempnam: cdecl cstr (ptr, ptr);
MSVCRT$_snwscanf: cdecl i32 (ptr, size_t, ptr, ...);
MSVCRT$_wfdopen: cdecl ptr (i32, ptr);
MSVCRT$_wfopen: cdecl ptr (ptr, ptr);
MSVCRT$_wfreopen: cdecl ptr (ptr, ptr, ptr);
MSVCRT$_wperror: cdecl void (ptr);
MSVCRT$_wpopen: cdecl ptr (ptr, ptr);
MSVCRT$_wremove: cdecl i32 (ptr);
MSVCRT$_wtmpnam: cdecl cstr (ptr);
MSVCRT$_fgetwc_nolock: cdecl u32 (ptr);
MSVCRT$_fputwc_nolock: cdecl u32 (u16, ptr);
MSVCRT$_ungetwc_nolock: cdecl u32 (u32, ptr);
MSVCRT$_fgetc_nolock: cdecl i32 (ptr);
MSVCRT$_fputc_nolock: cdecl i32 (i32, ptr);
MSVCRT$_getc_nolock: cdecl i32 (ptr);
MSVCRT$_putc_nolock: cdecl i32 (i32, ptr);
MSVCRT$_lock_file: cdecl void (ptr);
MSVCRT$_unlock_file: cdecl void (ptr);
MSVCRT$_fclose_nolock: cdecl i32 (ptr);
MSVCRT$_fflush_nolock: cdecl i32 (ptr);
MSVCRT$_fread_nolock: cdecl size_t (ptr, size_t, size_t, ptr);
MSVCRT$_fseek_nolock: cdecl i32 (ptr, i32, i32);
MSVCRT$_ftell_nolock: cdecl i32 (ptr);
MSVCRT$_fseeki64_nolock: cdecl i32 (ptr, i64, i32);
MSVCRT$_ftelli64_nolock: cdecl i64 (ptr);
MSVCRT$_fwrite_nolock: cdecl size_t (ptr, size_t, size_t, ptr);
MSVCRT$_ungetc_nolock: cdecl i32 (i32, ptr);
MSVCRT$tempnam: cdecl cstr (cstr, cstr);
MSVCRT$fcloseall: cdecl i32 ();
MSVCRT$fgetchar: cdecl i32 ();
MSVCRT$flushall: cdecl i32 ();
MSVCRT$fputchar: cdecl i32 (i32);
MSVCRT$getw: cdecl i32 (ptr);
MSVCRT$putw: cdecl i32 (i32, ptr);
MSVCRT$rmtmp: cdecl i32 ();
MSVCRT$_wspawnl: cdecl size_t (i32, ptr, ptr, ...);
MSVCRT$_wspawnle: cdecl size_t (i32, ptr, ptr, ...);
MSVCRT$_wspawnlp: cdecl size_t (i32, ptr, ptr, ...);
MSVCRT$_wspawnlpe: cdecl size_t (i32, ptr, ptr, ...);
MSVCRT$_wspawnv: cdecl size_t (i32, ptr, ptr);
MSVCRT$_wspawnve: cdecl size_t (i32, ptr, ptr, ptr);
MSVCRT$_wspawnvp: cdecl size_t (i32, ptr, ptr);
MSVCRT$_wspawnvpe: cdecl size_t (i32, ptr, ptr, ptr);
MSVCRT$_spawnv: cdecl size_t (i32, cstr, cstr);
MSVCRT$_spawnve: cdecl size_t (i32, cstr, cstr, cstr);
MSVCRT$_spawnvp: cdecl size_t (i32, cstr, cstr);
MSVCRT$_spawnvpe: cdecl size_t (i32, cstr, cstr, cstr);
MSVCRT$_memccpy: cdecl ptr (ptr, ptr, i32, size_t);
MSVCRT$memchr: cdecl ptr (ptr, i32, size_t);
MSVCRT$_memicmp: cdecl i32 (ptr, ptr, size_t);
MSVCRT$_memicmp_l: cdecl i32 (ptr, ptr, size_t, ptr);
MSVCRT$memcmp: cdecl i32 (ptr, ptr, size_t);
MSVCRT$memcpy: cdecl ptr (ptr, ptr, size_t);
MSVCRT$memcpy_s: cdecl i32 (ptr, size_t, ptr, size_t);
MSVCRT$mempcpy: cdecl ptr (ptr, ptr, size_t);
MSVCRT$memset: cdecl ptr (ptr, i32, size_t);
MSVCRT$memccpy: cdecl ptr (ptr, ptr, i32, size_t);
MSVCRT$memicmp: cdecl i32 (ptr, ptr, size_t);
MSVCRT$_errno: cdecl ptr ();
MSVCRT$_set_errno: cdecl i32 (i32);
MSVCRT$_get_errno: cdecl i32 (ptr);
MSVCRT$_set_doserrno: cdecl i32 (u32);
MSVCRT$_get_doserrno: cdecl i32 (ptr);
MSVCRT$_get_pgmptr: cdecl i32 (ptr);
MSVCRT$_get_wpgmptr: cdecl i32 (ptr);
MSVCRT$_set_fmode: cdecl i32 (i32);
MSVCRT$_get_fmode: cdecl i32 (ptr);
MSVCRT$_get_environ: cdecl void (ptr);
MSVCRT$_get_wenviron: cdecl void (ptr);
MSVCRT$_get_osplatform: cdecl i32 (ptr);
MSVCRT$_get_osver: cdecl i32 (ptr);
MSVCRT$_get_winver: cdecl i32 (ptr);
MSVCRT$_get_winmajor: cdecl i32 (ptr);
MSVCRT$_get_winminor: cdecl i32 (ptr);
MSVCRT$_Exit: cdecl void (i32);
MSVCRT$_set_abort_behavior: cdecl u32 (u32, u32);
MSVCRT$abs: cdecl i32 (i32);
MSVCRT$labs: cdecl i32 (i32);
MSVCRT$_abs64: cdecl i64 (i64);
MSVCRT$atexit: cdecl i32 (ptr);
MSVCRT$atoi: cdecl i32 (cstr);
MSVCRT$_atoi_l: cdecl i32 (cstr, ptr);
MSVCRT$atol: cdecl i32 (cstr);
MSVCRT$_atol_l: cdecl i32 (cstr, ptr);
MSVCRT$bsearch: cdecl ptr (ptr, ptr, size_t, size_t, ptr);
MSVCRT$qsort: cdecl void (ptr, size_t, size_t, ptr);
MSVCRT$_byteswap_ushort: cdecl u16 (u16);
MSVCRT$_byteswap_ulong: cdecl u32 (u32);
MSVCRT$_byteswap_uint64: cdecl u64 (u64);
MSVCRT$getenv: cdecl cstr (cstr);
MSVCRT$_itoa: cdecl cstr (i32, ptr, i32);
MSVCRT$_i64toa: cdecl cstr (i64, ptr, i32);
MSVCRT$_ui64toa: cdecl cstr (u64, ptr, i32);
MSVCRT$_atoi64: cdecl i64 (cstr);
MSVCRT$_atoi64_l: cdecl i64 (cstr, ptr);
MSVCRT$_strtoi64: cdecl i64 (cstr, ptr, i32);
MSVCRT$_strtoi64_l: cdecl i64 (cstr, ptr, i32, ptr);
MSVCRT$_strtoui64: cdecl u64 (cstr, ptr, i32);
MSVCRT$_strtoui64_l: cdecl u64 (cstr, ptr, i32, ptr);
MSVCRT$_ltoa: cdecl cstr (i32, ptr, i32);
MSVCRT$mblen: cdecl i32 (cstr, size_t);
MSVCRT$_mblen_l: cdecl i32 (cstr, size_t, ptr);
MSVCRT$_mbstrlen: cdecl size_t (cstr);
MSVCRT$_mbstrlen_l: cdecl size_t (cstr, ptr);
MSVCRT$_mbstrnlen: cdecl size_t (cstr, size_t);
MSVCRT$_mbstrnlen_l: cdecl size_t (cstr, size_t, ptr);
MSVCRT$mbtowc: cdecl i32 (ptr, cstr, size_t);
MSVCRT$_mbtowc_l: cdecl i32 (ptr, cstr, size_t, ptr);
MSVCRT$mbstowcs: cdecl size_t (ptr, cstr, size_t);
MSVCRT$_mbstowcs_l: cdecl size_t (ptr, cstr, size_t, ptr);
MSVCRT$mkstemp: cdecl i32 (ptr);
MSVCRT$rand: cdecl i32 ();
MSVCRT$_set_error_mode: cdecl i32 (i32);
MSVCRT$srand: cdecl void (u32);
MSVCRT$rand_s: cdecl i32 (ptr);
MSVCRT$strtol: cdecl i32 (cstr, ptr, i32);
MSVCRT$_strtol_l: cdecl i32 (cstr, ptr, i32, ptr);
MSVCRT$strtoul: cdecl u32 (cstr, ptr, i32);
MSVCRT$_strtoul_l: cdecl u32 (cstr, ptr, i32, ptr);
MSVCRT$system: cdecl i32 (cstr);
MSVCRT$_ultoa: cdecl cstr (u32, ptr, i32);
MSVCRT$wctomb: cdecl i32 (ptr, u16);
MSVCRT$_wctomb_l: cdecl i32 (ptr, u16, ptr);
MSVCRT$wcstombs: cdecl size_t (ptr, ptr, size_t);
MSVCRT$_wcstombs_l: cdecl size_t (ptr, ptr, size_t, ptr);
MSVCRT$calloc: cdecl ptr (size_t, size_t);
MSVCRT$free: cdecl void (ptr);
MSVCRT$malloc: cdecl ptr (size_t);
MSVCRT$realloc: cdecl ptr (ptr, size_t);
MSVCRT$_recalloc: cdecl ptr (ptr, size_t, size_t);
MSVCRT$_aligned_free: cdecl void (ptr);
MSVCRT$_aligned_malloc: cdecl ptr (size_t, size_t);
MSVCRT$_aligned_offset_malloc: cdecl ptr (size_t, size_t, size_t);
MSVCRT$_aligned_realloc: cdecl ptr (ptr, size_t, size_t);
MSVCRT$_aligned_recalloc: cdecl ptr (ptr, size_t, size_t, size_t);
MSVCRT$_aligned_offset_realloc: cdecl ptr (ptr, size_t, size_t, size_t);
MSVCRT$_aligned_offset_recalloc: cdecl ptr (ptr, size_t, size_t, size_t, size_t);
MSVCRT$_itow: cdecl cstr (i32, ptr, i32);
MSVCRT$_ltow: cdecl cstr (i32, ptr, i32);
MSVCRT$_ultow: cdecl cstr (u32, ptr, i32);
MSVCRT$wcstold: cdecl i32 (ptr, ptr);
MSVCRT$wcstol: cdecl i32 (ptr, ptr, i32);
MSVCRT$_wcstol_l: cdecl i32 (ptr, ptr, i32, ptr);
MSVCRT$wcstoul: cdecl u32 (ptr, ptr, i32);
MSVCRT$_wcstoul_l: cdecl u32 (ptr, ptr, i32, ptr);
MSVCRT$_wgetenv: cdecl cstr (ptr);
MSVCRT$_wsystem: cdecl i32 (ptr);
MSVCRT$_wtoi: cdecl i32 (ptr);
MSVCRT$_wtoi_l: cdecl i32 (ptr, ptr);
MSVCRT$_wtol: cdecl i32 (ptr);
MSVCRT$_wtol_l: cdecl i32 (ptr, ptr);
MSVCRT$_i64tow: cdecl cstr (i64, ptr, i32);
MSVCRT$_ui64tow: cdecl cstr (u64, ptr, i32);
MSVCRT$_wtoi64: cdecl i64 (ptr);
MSVCRT$_wtoi64_l: cdecl i64 (ptr, ptr);
MSVCRT$_wcstoi64: cdecl i64 (ptr, ptr, i32);
MSVCRT$_wcstoi64_l: cdecl i64 (ptr, ptr, i32, ptr);
MSVCRT$_wcstoui64: cdecl u64 (ptr, ptr, i32);
MSVCRT$_wcstoui64_l: cdecl u64 (ptr, ptr, i32, ptr);
MSVCRT$_putenv: cdecl i32 (cstr);
MSVCRT$_wputenv: cdecl i32 (ptr);
MSVCRT$_fullpath: cdecl cstr (ptr, cstr, size_t);
MSVCRT$_atodbl: cdecl i32 (ptr, ptr);
MSVCRT$_atoldbl: cdecl i32 (ptr, ptr);
MSVCRT$_atoflt: cdecl i32 (ptr, ptr);
MSVCRT$_atodbl_l: cdecl i32 (ptr, ptr, ptr);
MSVCRT$_atoldbl_l: cdecl i32 (ptr, ptr, ptr);
MSVCRT$_atoflt_l: cdecl i32 (ptr, ptr, ptr);
MSVCRT$_lrotl: cdecl u32 (u32, i32);
MSVCRT$_lrotr: cdecl u32 (u32, i32);
MSVCRT$_makepath: cdecl void (ptr, cstr, cstr, cstr, cstr);
MSVCRT$_onexit: cdecl ptr (ptr);
MSVCRT$_rotl64: cdecl u64 (u64, i32);
MSVCRT$_rotr64: cdecl u64 (u64, i32);
MSVCRT$_rotr: cdecl u32 (u32, i32);
MSVCRT$_rotl: cdecl u32 (u32, i32);
MSVCRT$_searchenv: cdecl void (cstr, cstr, ptr);
MSVCRT$_splitpath: cdecl void (cstr, ptr, ptr, ptr, ptr);
MSVCRT$_swab: cdecl void (ptr, ptr, i32);
MSVCRT$_wfullpath: cdecl cstr (ptr, ptr, size_t);
MSVCRT$_wmakepath: cdecl void (ptr, ptr, ptr, ptr, ptr);
MSVCRT$_wsearchenv: cdecl void (ptr, ptr, ptr);
MSVCRT$_wsplitpath: cdecl void (ptr, ptr, ptr, ptr, ptr);
MSVCRT$_seterrormode: cdecl void (i32);
MSVCRT$_sleep: cdecl void (u32);
MSVCRT$itoa: cdecl cstr (i32, ptr, i32);
MSVCRT$ltoa: cdecl cstr (i32, ptr, i32);
MSVCRT$putenv: cdecl i32 (cstr);
MSVCRT$swab: cdecl void (ptr, ptr, i32);
MSVCRT$ultoa: cdecl cstr (u32, ptr, i32);
MSVCRT$onexit: cdecl ptr (ptr);
MSVCRT$llabs: cdecl i64 (i64);
MSVCRT$strtoll: cdecl i64 (cstr, ptr, i32);
MSVCRT$strtoull: cdecl u64 (cstr, ptr, i32);
MSVCRT$atoll: cdecl i64 (cstr);
MSVCRT$wtoll: cdecl i64 (ptr);
MSVCRT$lltoa: cdecl cstr (i64, ptr, i32);
MSVCRT$ulltoa: cdecl cstr (u64, ptr, i32);
MSVCRT$lltow: cdecl cstr (i64, ptr, i32);
MSVCRT$ulltow: cdecl cstr (u64, ptr, i32);
MSVCRT$_strset: cdecl cstr (ptr, i32);
MSVCRT$_strset_l: cdecl cstr (ptr, i32, ptr);
MSVCRT$strcpy: cdecl cstr (ptr, cstr);
MSVCRT$strcat: cdecl cstr (ptr, cstr);
MSVCRT$strcmp: cdecl i32 (cstr, cstr);
MSVCRT$strlen: cdecl size_t (cstr);
MSVCRT$strnlen: cdecl size_t (cstr, size_t);
MSVCRT$memmove: cdecl ptr (ptr, ptr, size_t);
MSVCRT$_strdup: cdecl cstr (cstr);
MSVCRT$strchr: cdecl cstr (cstr, i32);
MSVCRT$_stricmp: cdecl i32 (cstr, cstr);
MSVCRT$_strcmpi: cdecl i32 (cstr, cstr);
MSVCRT$_stricmp_l: cdecl i32 (cstr, cstr, ptr);
MSVCRT$strcoll: cdecl i32 (cstr, cstr);
MSVCRT$_strcoll_l: cdecl i32 (cstr, cstr, ptr);
MSVCRT$_stricoll: cdecl i32 (cstr, cstr);
MSVCRT$_stricoll_l: cdecl i32 (cstr, cstr, ptr);
MSVCRT$_strncoll: cdecl i32 (cstr, cstr, size_t);
MSVCRT$_strncoll_l: cdecl i32 (cstr, cstr, size_t, ptr);
MSVCRT$_strnicoll: cdecl i32 (cstr, cstr, size_t);
MSVCRT$_strnicoll_l: cdecl i32 (cstr, cstr, size_t, ptr);
MSVCRT$strcspn: cdecl size_t (cstr, cstr);
MSVCRT$_strerror: cdecl cstr (cstr);
MSVCRT$strerror: cdecl cstr (i32);
MSVCRT$_strlwr: cdecl cstr (ptr);
MSVCRT$strncat: cdecl cstr (ptr, cstr, size_t);
MSVCRT$strncmp: cdecl i32 (cstr, cstr, size_t);
MSVCRT$_strnicmp: cdecl i32 (cstr, cstr, size_t);
MSVCRT$_strnicmp_l: cdecl i32 (cstr, cstr, size_t, ptr);
MSVCRT$_strnset: cdecl cstr (ptr, i32, size_t);
MSVCRT$_strnset_l: cdecl cstr (ptr, i32, size_t, ptr);
MSVCRT$strpbrk: cdecl cstr (cstr, cstr);
MSVCRT$strrchr: cdecl cstr (cstr, i32);
MSVCRT$_strrev: cdecl cstr (ptr);
MSVCRT$strspn: cdecl size_t (cstr, cstr);
MSVCRT$strstr: cdecl cstr (cstr, cstr);
MSVCRT$strtok: cdecl cstr (ptr, cstr);
MSVCRT$_strupr: cdecl cstr (ptr);
MSVCRT$strxfrm: cdecl size_t (ptr, cstr, size_t);
MSVCRT$_strxfrm_l: cdecl size_t (ptr, cstr, size_t, ptr);
MSVCRT$strdup: cdecl cstr (cstr);
MSVCRT$strcmpi: cdecl i32 (cstr, cstr);
MSVCRT$stricmp: cdecl i32 (cstr, cstr);
MSVCRT$strlwr: cdecl cstr (ptr);
MSVCRT$strnicmp: cdecl i32 (cstr, cstr, size_t);
MSVCRT$strncasecmp: cdecl i32 (cstr, cstr, size_t);
MSVCRT$strcasecmp: cdecl i32 (cstr, cstr);
MSVCRT$strnset: cdecl cstr (ptr, i32, size_t);
MSVCRT$strrev: cdecl cstr (ptr);
MSVCRT$strset: cdecl cstr (ptr, i32);
MSVCRT$strupr: cdecl cstr (ptr);
MSVCRT$_wcsdup: cdecl cstr (ptr);
MSVCRT$wcscat: cdecl cstr (ptr, ptr);
MSVCRT$wcschr: cdecl cstr (ptr, u16);
MSVCRT$wcscmp: cdecl i32 (ptr, ptr);
MSVCRT$wcscpy: cdecl cstr (ptr, ptr);
MSVCRT$wcscspn: cdecl size_t (ptr, ptr);
MSVCRT$wcslen: cdecl size_t (ptr);
MSVCRT$wcsnlen: cdecl size_t (ptr, size_t);
MSVCRT$wcsncmp: cdecl i32 (ptr, ptr, size_t);
MSVCRT$_wcsncpy_l: cdecl cstr (ptr, ptr, size_t, ptr);
MSVCRT$wcspbrk: cdecl cstr (ptr, ptr);
MSVCRT$wcsrchr: cdecl cstr (ptr, u16);
MSVCRT$wcsspn: cdecl size_t (ptr, ptr);
MSVCRT$wcsstr: cdecl cstr (ptr, ptr);
MSVCRT$wcstok: cdecl cstr (ptr, ptr);
MSVCRT$_wcserror: cdecl cstr (i32);
MSVCRT$_wcsicmp: cdecl i32 (ptr, ptr);
MSVCRT$_wcsicmp_l: cdecl i32 (ptr, ptr, ptr);
MSVCRT$_wcsnicmp: cdecl i32 (ptr, ptr, size_t);
MSVCRT$_wcsnicmp_l: cdecl i32 (ptr, ptr, size_t, ptr);
MSVCRT$_wcsnset: cdecl cstr (ptr, u16, size_t);
MSVCRT$_wcsrev: cdecl cstr (ptr);
MSVCRT$_wcsset: cdecl cstr (ptr, u16);
MSVCRT$_wcslwr: cdecl cstr (ptr);
MSVCRT$_wcsupr: cdecl cstr (ptr);
MSVCRT$wcsxfrm: cdecl size_t (ptr, ptr, size_t);
MSVCRT$_wcsxfrm_l: cdecl size_t (ptr, ptr, size_t, ptr);
MSVCRT$wcscoll: cdecl i32 (ptr, ptr);
MSVCRT$_wcscoll_l: cdecl i32 (ptr, ptr, ptr);
MSVCRT$_wcsicoll: cdecl i32 (ptr, ptr);
MSVCRT$_wcsicoll_l: cdecl i32 (ptr, ptr, ptr);
MSVCRT$_wcsncoll: cdecl i32 (ptr, ptr, size_t);
MSVCRT$_wcsncoll_l: cdecl i32 (ptr, ptr, size_t, ptr);
MSVCRT$_wcsnicoll: cdecl i32 (ptr, ptr, size_t);
MSVCRT$_wcsnicoll_l: cdecl i32 (ptr, ptr, size_t, ptr);
MSVCRT$wcsdup: cdecl cstr (ptr);
MSVCRT$wcsicmp: cdecl i32 (ptr, ptr);
MSVCRT$wcsnicmp: cdecl i32 (ptr, ptr, size_t);
MSVCRT$wcsnset: cdecl cstr (ptr, u16, size_t);
MSVCRT$wcsrev: cdecl cstr (ptr);
MSVCRT$wcsset: cdecl cstr (ptr, u16);
MSVCRT$wcslwr: cdecl cstr (ptr);
MSVCRT$wcsupr: cdecl cstr (ptr);
MSVCRT$wcsicoll: cdecl i32 (ptr, ptr);

#endif /* BUILTINS_MSVCRT_H */
