#ifndef BUILTINS_NTAPI_H
#define BUILTINS_NTAPI_H

NTDLL$NtQueryObject: i32 (ptr, i32, ptr, u32, ptr);
NTDLL$NtOpenThreadToken: i32 (ptr, u32, u32, ptr);
NTDLL$NtOpenProcessToken: i32 (ptr, u32, ptr);
NTDLL$NtQueryInformationToken: i32 (ptr, i32, ptr, u32, ptr);
NTDLL$NtAdjustPrivilegesToken: i32 (ptr, u32, ptr, u32, ptr, ptr);
NTDLL$NtCreateFile: i32 (ptr, u32, ptr, ptr, ptr, u32, u32, u32, u32, ptr, u32);
NTDLL$NtDeviceIoControlFile: i32 (ptr, ptr, ptr, ptr, ptr, u32, ptr, u32, ptr, u32);
NTDLL$NtFsControlFile: i32 (ptr, ptr, ptr, ptr, ptr, u32, ptr, u32, ptr, u32);
NTDLL$NtLockFile: i32 (ptr, ptr, ptr, ptr, ptr, ptr, ptr, u32, u32, u32);
NTDLL$NtOpenFile: i32 (ptr, u32, ptr, ptr, u32, u32);
NTDLL$NtQueryDirectoryFile: i32 (ptr, ptr, ptr, ptr, ptr, ptr, u32, i32, u32, ptr, u32);
NTDLL$NtQueryInformationFile: i32 (ptr, ptr, ptr, u32, i32);
NTDLL$NtQueryQuotaInformationFile: i32 (ptr, ptr, ptr, u32, u32, ptr, u32, ptr, u32);
NTDLL$NtQueryVolumeInformationFile: i32 (ptr, ptr, ptr, u32, i32);
NTDLL$NtReadFile: i32 (ptr, ptr, ptr, ptr, ptr, ptr, u32, ptr, ptr);
NTDLL$NtSetInformationFile: i32 (ptr, ptr, ptr, u32, i32);
NTDLL$NtSetQuotaInformationFile: i32 (ptr, ptr, ptr, u32);
NTDLL$NtSetVolumeInformationFile: i32 (ptr, ptr, ptr, u32, i32);
NTDLL$NtWriteFile: i32 (ptr, ptr, ptr, ptr, ptr, ptr, u32, ptr, ptr);
NTDLL$NtUnlockFile: i32 (ptr, ptr, ptr, ptr, u32);
NTDLL$NtSetSecurityObject: i32 (ptr, u32, ptr);
NTDLL$NtQuerySecurityObject: i32 (ptr, u32, ptr, u32, ptr);
NTDLL$NtClose: i32 (ptr);
NTDLL$NtAllocateVirtualMemory: i32 (ptr, ptr, size_t, ptr, u32, u32);
NTDLL$NtReadVirtualMemory: i32 (ptr, ptr, ptr, size_t, ptr);
NTDLL$NtWriteVirtualMemory: i32 (ptr, ptr, ptr, size_t, ptr);
NTDLL$NtProtectVirtualMemory: i32 (ptr, ptr, ptr, u32, ptr);
NTDLL$NtQueryVirtualMemory: i32 (ptr, ptr, i32, ptr, size_t, ptr);
NTDLL$NtFreeVirtualMemory: i32 (ptr, ptr, ptr, u32);
NTDLL$NtOpenThreadTokenEx: i32 (ptr, u32, u32, u32, ptr);
NTDLL$NtOpenProcessTokenEx: i32 (ptr, u32, u32, ptr);
NTDLL$NtDuplicateToken: i32 (ptr, u32, ptr, u32, i32, ptr);
NTDLL$NtFilterToken: i32 (ptr, u32, ptr, ptr, ptr, ptr);
NTDLL$NtImpersonateAnonymousToken: i32 (ptr);
NTDLL$NtSetInformationToken: i32 (ptr, i32, ptr, u32);
NTDLL$NtAdjustGroupsToken: i32 (ptr, u32, ptr, u32, ptr, ptr);
NTDLL$NtPrivilegeCheck: i32 (ptr, ptr, ptr);
NTDLL$NtAccessCheckAndAuditAlarm: i32 (ptr, ptr, ptr, ptr, ptr, u32, ptr, u32, ptr, ptr, ptr);
NTDLL$NtAccessCheckByTypeAndAuditAlarm: i32 (ptr, ptr, ptr, ptr, ptr, ptr, u32, i32, u32, ptr, u32, ptr, u32, ptr, ptr, ptr);
NTDLL$NtAccessCheckByTypeResultListAndAuditAlarm: i32 (ptr, ptr, ptr, ptr, ptr, ptr, u32, i32, u32, ptr, u32, ptr, u32, ptr, ptr, ptr);
NTDLL$NtOpenObjectAuditAlarm: i32 (ptr, ptr, ptr, ptr, ptr, ptr, u32, u32, ptr, u32, u32, ptr);
NTDLL$NtPrivilegeObjectAuditAlarm: i32 (ptr, ptr, ptr, u32, ptr, u32);
NTDLL$NtCloseObjectAuditAlarm: i32 (ptr, ptr, u32);
NTDLL$NtDeleteObjectAuditAlarm: i32 (ptr, ptr, u32);
NTDLL$NtPrivilegedServiceAuditAlarm: i32 (ptr, ptr, ptr, ptr, u32);
NTDLL$NtSetInformationThread: i32 (ptr, u32, ptr, u32);
NTDLL$NtCreateSection: i32 (ptr, u32, ptr, ptr, u32, u32, ptr);
NTDLL$NtOpenSection: i32 (ptr, u32, ptr);
NTDLL$NtMapViewOfSection: i32 (ptr, ptr, ptr, size_t, size_t, ptr, ptr, u32, u32, u32);
NTDLL$NtUnmapViewOfSection: i32 (ptr, ptr);
NTDLL$NtQueryInformationProcess: i32 (ptr, u32, ptr, u32, ptr);
NTDLL$NtQueryInformationThread: i32 (ptr, u32, ptr, u32, ptr);
NTDLL$NtGetContextThread: i32 (ptr, ptr);
NTDLL$NtSetContextThread: i32 (ptr, ptr);
NTDLL$NtResumeThread: i32 (ptr, ptr);
NTDLL$NtCreateThreadEx: i32 (ptr, u32, ptr, ptr, ptr, ptr, u32, size_t, size_t, size_t, ptr);
NTDLL$NtOpenProcess: i32 (ptr, u32, ptr, ptr);
NTDLL$NtOpenThread: i32 (ptr, u32, ptr, ptr);
NTDLL$NtDuplicateObject: i32 (ptr, ptr, ptr, ptr, u32, u32, u32);
NTDLL$NtQueueApcThread: i32 (ptr, ptr, ptr, ptr, ptr);
NTDLL$NtCreateProcess: i32 (ptr, u32, ptr, ptr, i32, ptr, ptr, ptr);
NTDLL$NtSuspendProcess: i32 (ptr);
NTDLL$NtResumeProcess: i32 (ptr);
NTDLL$NtQuerySystemInformation: i32 (u32, ptr, u32, ptr);
NTDLL$NtSetInformationProcess: i32 (ptr, u32, ptr, u32);
NTDLL$NtWaitForMultipleObjects: i32 (u32, ptr, u32, i32, ptr);
NTDLL$NtWaitForSingleObject: i32 (ptr, i32, ptr);
NTDLL$RtlInitUnicodeString: void (ptr, ptr);
NTDLL$RtlGetCurrentPeb: ptr ();
NTDLL$RtlCreateUserThread: i32 (ptr, ptr, u32, u32, size_t, size_t, ptr, ptr, ptr, ptr);
NTDLL$RtlCreateUserProcess: i32 (ptr, u32, ptr, ptr, ptr, ptr, u32, ptr, ptr, ptr);
NTDLL$RtlCreateUserProcessEx: i32 (ptr, ptr, u32, ptr, ptr);
NTDLL$RtlQueueWorkItem: i32 (ptr, ptr, u32);
NTDLL$RtlRegisterWait: i32 (ptr, ptr, ptr, ptr, u32, u32);
NTDLL$RtlRandom: u32 (ptr);
NTDLL$RtlRandomEx: u32 (ptr);
NTDLL$NtContinue: i32 (ptr, u32);
NTDLL$RtlZeroMemory: void (ptr, size_t);
NTDLL$NtAlertResumeThread: i32 (ptr, ptr);
NTDLL$NtAlertThread: i32 (ptr);

#endif
