#ifndef BUILTINS_SHLWAPI_H
#define BUILTINS_SHLWAPI_H

SHLWAPI$StrChrA: ptr (cstr, u16);
SHLWAPI$StrChrW: ptr (ptr, u16);
SHLWAPI$StrChrIA: ptr (cstr, u16);
SHLWAPI$StrChrIW: ptr (ptr, u16);
SHLWAPI$StrCmpNA: i32 (cstr, cstr, i32);
SHLWAPI$StrCmpNW: i32 (ptr, ptr, i32);
SHLWAPI$StrCmpNIA: i32 (cstr, cstr, i32);
SHLWAPI$StrCmpNIW: i32 (ptr, ptr, i32);
SHLWAPI$StrCSpnA: i32 (cstr, cstr);
SHLWAPI$StrCSpnW: i32 (ptr, ptr);
SHLWAPI$StrCSpnIA: i32 (cstr, cstr);
SHLWAPI$StrCSpnIW: i32 (ptr, ptr);
SHLWAPI$StrDupA: ptr (cstr);
SHLWAPI$StrDupW: ptr (ptr);
SHLWAPI$StrFormatByteSizeA: ptr (u32, ptr, u32);
SHLWAPI$StrFormatByteSize64A: ptr (i64, ptr, u32);
SHLWAPI$StrFormatByteSizeW: ptr (i64, ptr, u32);
SHLWAPI$StrFormatKBSizeW: ptr (i64, ptr, u32);
SHLWAPI$StrFormatKBSizeA: ptr (i64, ptr, u32);
SHLWAPI$StrFromTimeIntervalA: i32 (ptr, u32, u32, i32);
SHLWAPI$StrFromTimeIntervalW: i32 (ptr, u32, u32, i32);
SHLWAPI$StrIsIntlEqualA: u32 (u32, cstr, cstr, i32);
SHLWAPI$StrIsIntlEqualW: u32 (u32, ptr, ptr, i32);
SHLWAPI$StrNCatA: ptr (ptr, cstr, i32);
SHLWAPI$StrNCatW: ptr (ptr, ptr, i32);
SHLWAPI$StrPBrkA: ptr (cstr, cstr);
SHLWAPI$StrPBrkW: ptr (ptr, ptr);
SHLWAPI$StrRChrA: ptr (cstr, cstr, u16);
SHLWAPI$StrRChrW: ptr (ptr, ptr, u16);
SHLWAPI$StrRChrIA: ptr (cstr, cstr, u16);
SHLWAPI$StrRChrIW: ptr (ptr, ptr, u16);
SHLWAPI$StrRStrIA: ptr (cstr, cstr, cstr);
SHLWAPI$StrRStrIW: ptr (ptr, ptr, ptr);
SHLWAPI$StrSpnA: i32 (cstr, cstr);
SHLWAPI$StrSpnW: i32 (ptr, ptr);
SHLWAPI$StrStrA: ptr (cstr, cstr);
SHLWAPI$StrStrW: ptr (ptr, ptr);
SHLWAPI$StrStrIA: ptr (cstr, cstr);
SHLWAPI$StrStrIW: ptr (ptr, ptr);
SHLWAPI$StrToIntA: i32 (cstr);
SHLWAPI$StrToIntW: i32 (ptr);
SHLWAPI$StrToIntExA: u32 (cstr, u32, ptr);
SHLWAPI$StrToIntExW: u32 (ptr, u32, ptr);
SHLWAPI$StrToInt64ExA: u32 (cstr, u32, ptr);
SHLWAPI$StrToInt64ExW: u32 (ptr, u32, ptr);
SHLWAPI$StrTrimA: u32 (ptr, cstr);
SHLWAPI$StrTrimW: u32 (ptr, ptr);
SHLWAPI$StrCatW: ptr (ptr, ptr);
SHLWAPI$StrCmpW: i32 (ptr, ptr);
SHLWAPI$StrCmpIW: i32 (ptr, ptr);
SHLWAPI$StrCpyW: ptr (ptr, ptr);
SHLWAPI$StrCpyNW: ptr (ptr, ptr, i32);
SHLWAPI$StrCatBuffW: ptr (ptr, ptr, i32);
SHLWAPI$StrCatBuffA: ptr (ptr, cstr, i32);
SHLWAPI$ChrCmpIA: u32 (u16, u16);
SHLWAPI$ChrCmpIW: u32 (u16, u16);
SHLWAPI$wvnsprintfA: i32 (ptr, i32, cstr, ptr);
SHLWAPI$wvnsprintfW: i32 (ptr, i32, ptr, ptr);
SHLWAPI$StrCmpLogicalW: i32 (ptr, ptr);
SHLWAPI$StrCatChainW: u32 (ptr, u32, u32, ptr);
SHLWAPI$IsCharSpaceA: u32 (u32);
SHLWAPI$IsCharSpaceW: u32 (u16);
SHLWAPI$StrCmpCA: i32 (cstr, cstr);
SHLWAPI$StrCmpCW: i32 (ptr, ptr);
SHLWAPI$StrCmpICA: i32 (cstr, cstr);
SHLWAPI$StrCmpICW: i32 (ptr, ptr);
SHLWAPI$IntlStrEqWorkerA: u32 (u32, cstr, cstr, i32);
SHLWAPI$IntlStrEqWorkerW: u32 (u32, ptr, ptr, i32);
SHLWAPI$PathAddBackslashA: ptr (ptr);
SHLWAPI$PathAddBackslashW: ptr (ptr);
SHLWAPI$PathAddExtensionA: u32 (ptr, cstr);
SHLWAPI$PathAddExtensionW: u32 (ptr, ptr);
SHLWAPI$PathAppendA: u32 (ptr, cstr);
SHLWAPI$PathAppendW: u32 (ptr, ptr);
SHLWAPI$PathBuildRootA: ptr (ptr, i32);
SHLWAPI$PathBuildRootW: ptr (ptr, i32);
SHLWAPI$PathCanonicalizeA: u32 (ptr, cstr);
SHLWAPI$PathCanonicalizeW: u32 (ptr, ptr);
SHLWAPI$PathCombineA: ptr (ptr, cstr, cstr);
SHLWAPI$PathCombineW: ptr (ptr, ptr, ptr);
SHLWAPI$PathCompactPathA: u32 (ptr, ptr, u32);
SHLWAPI$PathCompactPathW: u32 (ptr, ptr, u32);
SHLWAPI$PathCompactPathExA: u32 (ptr, cstr, u32, u32);
SHLWAPI$PathCompactPathExW: u32 (ptr, ptr, u32, u32);
SHLWAPI$PathCommonPrefixA: i32 (cstr, cstr, ptr);
SHLWAPI$PathCommonPrefixW: i32 (ptr, ptr, ptr);
SHLWAPI$PathFileExistsA: u32 (cstr);
SHLWAPI$PathFileExistsW: u32 (ptr);
SHLWAPI$PathFindExtensionA: ptr (cstr);
SHLWAPI$PathFindExtensionW: ptr (ptr);
SHLWAPI$PathFindFileNameA: ptr (cstr);
SHLWAPI$PathFindFileNameW: ptr (ptr);
SHLWAPI$PathFindNextComponentA: ptr (cstr);
SHLWAPI$PathFindNextComponentW: ptr (ptr);
SHLWAPI$PathFindOnPathA: u32 (ptr, ptr);
SHLWAPI$PathFindOnPathW: u32 (ptr, ptr);
SHLWAPI$PathGetArgsA: ptr (cstr);
SHLWAPI$PathGetArgsW: ptr (ptr);
SHLWAPI$PathFindSuffixArrayA: cstr (cstr, ptr, i32);
SHLWAPI$PathFindSuffixArrayW: ptr (ptr, ptr, i32);
SHLWAPI$PathIsLFNFileSpecA: u32 (cstr);
SHLWAPI$PathIsLFNFileSpecW: u32 (ptr);
SHLWAPI$PathGetCharTypeA: u32 (u32);
SHLWAPI$PathGetCharTypeW: u32 (u16);
SHLWAPI$PathGetDriveNumberA: i32 (cstr);
SHLWAPI$PathGetDriveNumberW: i32 (ptr);
SHLWAPI$PathIsDirectoryA: u32 (cstr);
SHLWAPI$PathIsDirectoryW: u32 (ptr);
SHLWAPI$PathIsDirectoryEmptyA: u32 (cstr);
SHLWAPI$PathIsDirectoryEmptyW: u32 (ptr);
SHLWAPI$PathIsFileSpecA: u32 (cstr);
SHLWAPI$PathIsFileSpecW: u32 (ptr);
SHLWAPI$PathIsPrefixA: u32 (cstr, cstr);
SHLWAPI$PathIsPrefixW: u32 (ptr, ptr);
SHLWAPI$PathIsRelativeA: u32 (cstr);
SHLWAPI$PathIsRelativeW: u32 (ptr);
SHLWAPI$PathIsRootA: u32 (cstr);
SHLWAPI$PathIsRootW: u32 (ptr);
SHLWAPI$PathIsSameRootA: u32 (cstr, cstr);
SHLWAPI$PathIsSameRootW: u32 (ptr, ptr);
SHLWAPI$PathIsUNCA: u32 (cstr);
SHLWAPI$PathIsUNCW: u32 (ptr);
SHLWAPI$PathIsNetworkPathA: u32 (cstr);
SHLWAPI$PathIsNetworkPathW: u32 (ptr);
SHLWAPI$PathIsUNCServerA: u32 (cstr);
SHLWAPI$PathIsUNCServerW: u32 (ptr);
SHLWAPI$PathIsUNCServerShareA: u32 (cstr);
SHLWAPI$PathIsUNCServerShareW: u32 (ptr);
SHLWAPI$PathIsContentTypeA: u32 (cstr, cstr);
SHLWAPI$PathIsContentTypeW: u32 (ptr, ptr);
SHLWAPI$PathIsURLA: u32 (cstr);
SHLWAPI$PathIsURLW: u32 (ptr);
SHLWAPI$PathMakePrettyA: u32 (ptr);
SHLWAPI$PathMakePrettyW: u32 (ptr);
SHLWAPI$PathMatchSpecA: u32 (cstr, cstr);
SHLWAPI$PathMatchSpecW: u32 (ptr, ptr);
SHLWAPI$PathParseIconLocationA: i32 (ptr);
SHLWAPI$PathParseIconLocationW: i32 (ptr);
SHLWAPI$PathQuoteSpacesA: void (ptr);
SHLWAPI$PathQuoteSpacesW: void (ptr);
SHLWAPI$PathRelativePathToA: u32 (ptr, cstr, u32, cstr, u32);
SHLWAPI$PathRelativePathToW: u32 (ptr, ptr, u32, ptr, u32);
SHLWAPI$PathRemoveArgsA: void (ptr);
SHLWAPI$PathRemoveArgsW: void (ptr);
SHLWAPI$PathRemoveBackslashA: ptr (ptr);
SHLWAPI$PathRemoveBackslashW: ptr (ptr);
SHLWAPI$PathRemoveBlanksA: void (ptr);
SHLWAPI$PathRemoveBlanksW: void (ptr);
SHLWAPI$PathRemoveExtensionA: void (ptr);
SHLWAPI$PathRemoveExtensionW: void (ptr);
SHLWAPI$PathRemoveFileSpecA: u32 (ptr);
SHLWAPI$PathRemoveFileSpecW: u32 (ptr);
SHLWAPI$PathRenameExtensionA: u32 (ptr, cstr);
SHLWAPI$PathRenameExtensionW: u32 (ptr, ptr);
SHLWAPI$PathSearchAndQualifyA: u32 (cstr, ptr, u32);
SHLWAPI$PathSearchAndQualifyW: u32 (ptr, ptr, u32);
SHLWAPI$PathSetDlgItemPathA: void (ptr, i32, cstr);
SHLWAPI$PathSetDlgItemPathW: void (ptr, i32, ptr);
SHLWAPI$PathSkipRootA: ptr (cstr);
SHLWAPI$PathSkipRootW: ptr (ptr);
SHLWAPI$PathStripPathA: void (ptr);
SHLWAPI$PathStripPathW: void (ptr);
SHLWAPI$PathStripToRootA: u32 (ptr);
SHLWAPI$PathStripToRootW: u32 (ptr);
SHLWAPI$PathUnquoteSpacesA: void (ptr);
SHLWAPI$PathUnquoteSpacesW: void (ptr);
SHLWAPI$PathMakeSystemFolderA: u32 (cstr);
SHLWAPI$PathMakeSystemFolderW: u32 (ptr);
SHLWAPI$PathUnmakeSystemFolderA: u32 (cstr);
SHLWAPI$PathUnmakeSystemFolderW: u32 (ptr);
SHLWAPI$PathIsSystemFolderA: u32 (cstr, u32);
SHLWAPI$PathIsSystemFolderW: u32 (ptr, u32);
SHLWAPI$PathUndecorateA: void (ptr);
SHLWAPI$PathUndecorateW: void (ptr);
SHLWAPI$PathUnExpandEnvStringsA: u32 (cstr, ptr, u32);
SHLWAPI$PathUnExpandEnvStringsW: u32 (ptr, ptr, u32);
SHLWAPI$UrlCompareA: i32 (cstr, cstr, u32);
SHLWAPI$UrlCompareW: i32 (ptr, ptr, u32);
SHLWAPI$UrlIsOpaqueA: u32 (cstr);
SHLWAPI$UrlIsOpaqueW: u32 (ptr);
SHLWAPI$UrlIsNoHistoryA: u32 (cstr);
SHLWAPI$UrlIsNoHistoryW: u32 (ptr);
SHLWAPI$UrlIsA: u32 (cstr, u32);
SHLWAPI$UrlIsW: u32 (ptr, u32);
SHLWAPI$UrlGetLocationA: cstr (cstr);
SHLWAPI$UrlGetLocationW: ptr (ptr);
SHLWAPI$SHDeleteEmptyKeyA: u32 (ptr, cstr);
SHLWAPI$SHDeleteEmptyKeyW: u32 (ptr, ptr);
SHLWAPI$SHDeleteKeyA: u32 (ptr, cstr);
SHLWAPI$SHDeleteKeyW: u32 (ptr, ptr);
SHLWAPI$SHRegDuplicateHKey: ptr (ptr);
SHLWAPI$SHDeleteValueA: u32 (ptr, cstr, cstr);
SHLWAPI$SHDeleteValueW: u32 (ptr, ptr, ptr);
SHLWAPI$SHGetValueA: u32 (ptr, cstr, cstr, ptr, ptr, ptr);
SHLWAPI$SHGetValueW: u32 (ptr, ptr, ptr, ptr, ptr, ptr);
SHLWAPI$SHSetValueA: u32 (ptr, cstr, cstr, u32, ptr, u32);
SHLWAPI$SHSetValueW: u32 (ptr, ptr, ptr, u32, ptr, u32);
SHLWAPI$SHRegGetValueA: i32 (ptr, cstr, cstr, u32, ptr, ptr, ptr);
SHLWAPI$SHRegGetValueW: i32 (ptr, ptr, ptr, u32, ptr, ptr, ptr);
SHLWAPI$SHQueryValueExA: u32 (ptr, cstr, ptr, ptr, ptr, ptr);
SHLWAPI$SHQueryValueExW: u32 (ptr, ptr, ptr, ptr, ptr, ptr);
SHLWAPI$SHEnumKeyExA: i32 (ptr, u32, ptr, ptr);
SHLWAPI$SHEnumKeyExW: i32 (ptr, u32, ptr, ptr);
SHLWAPI$SHEnumValueA: i32 (ptr, u32, ptr, ptr, ptr, ptr, ptr);
SHLWAPI$SHEnumValueW: i32 (ptr, u32, ptr, ptr, ptr, ptr, ptr);
SHLWAPI$SHQueryInfoKeyA: i32 (ptr, ptr, ptr, ptr, ptr);
SHLWAPI$SHQueryInfoKeyW: i32 (ptr, ptr, ptr, ptr, ptr);
SHLWAPI$SHCopyKeyA: u32 (ptr, cstr, ptr, u32);
SHLWAPI$SHCopyKeyW: u32 (ptr, ptr, ptr, u32);
SHLWAPI$SHRegGetPathA: u32 (ptr, cstr, cstr, ptr, u32);
SHLWAPI$SHRegGetPathW: u32 (ptr, ptr, ptr, ptr, u32);
SHLWAPI$SHRegSetPathA: u32 (ptr, cstr, cstr, cstr, u32);
SHLWAPI$SHRegSetPathW: u32 (ptr, ptr, ptr, ptr, u32);
SHLWAPI$SHRegCreateUSKeyA: i32 (cstr, u32, ptr, ptr, u32);
SHLWAPI$SHRegCreateUSKeyW: i32 (ptr, u32, ptr, ptr, u32);
SHLWAPI$SHRegOpenUSKeyA: i32 (cstr, u32, ptr, ptr, u32);
SHLWAPI$SHRegOpenUSKeyW: i32 (ptr, u32, ptr, ptr, u32);
SHLWAPI$SHRegQueryUSValueA: i32 (ptr, cstr, ptr, ptr, ptr, u32, ptr, u32);
SHLWAPI$SHRegQueryUSValueW: i32 (ptr, ptr, ptr, ptr, ptr, u32, ptr, u32);
SHLWAPI$SHRegWriteUSValueA: i32 (ptr, cstr, u32, ptr, u32, u32);
SHLWAPI$SHRegWriteUSValueW: i32 (ptr, ptr, u32, ptr, u32, u32);
SHLWAPI$SHRegDeleteUSValueA: i32 (ptr, cstr, u32);
SHLWAPI$SHRegDeleteEmptyUSKeyW: i32 (ptr, ptr, u32);
SHLWAPI$SHRegDeleteEmptyUSKeyA: i32 (ptr, cstr, u32);
SHLWAPI$SHRegDeleteUSValueW: i32 (ptr, ptr, u32);
SHLWAPI$SHRegEnumUSKeyA: i32 (ptr, u32, ptr, ptr, u32);
SHLWAPI$SHRegEnumUSKeyW: i32 (ptr, u32, ptr, ptr, u32);
SHLWAPI$SHRegEnumUSValueA: i32 (ptr, u32, ptr, ptr, ptr, ptr, ptr, u32);
SHLWAPI$SHRegEnumUSValueW: i32 (ptr, u32, ptr, ptr, ptr, ptr, ptr, u32);
SHLWAPI$SHRegQueryInfoUSKeyA: i32 (ptr, ptr, ptr, ptr, ptr, u32);
SHLWAPI$SHRegQueryInfoUSKeyW: i32 (ptr, ptr, ptr, ptr, ptr, u32);
SHLWAPI$SHRegCloseUSKey: i32 (ptr);
SHLWAPI$SHRegGetUSValueA: i32 (cstr, cstr, ptr, ptr, ptr, u32, ptr, u32);
SHLWAPI$SHRegGetUSValueW: i32 (ptr, ptr, ptr, ptr, ptr, u32, ptr, u32);
SHLWAPI$SHRegSetUSValueA: i32 (cstr, cstr, u32, ptr, u32, u32);
SHLWAPI$SHRegSetUSValueW: i32 (ptr, ptr, u32, ptr, u32, u32);
SHLWAPI$SHRegGetIntW: i32 (ptr, ptr, i32);
SHLWAPI$SHRegGetBoolUSValueA: u32 (cstr, cstr, u32, u32);
SHLWAPI$SHRegGetBoolUSValueW: u32 (ptr, ptr, u32, u32);
SHLWAPI$AssocIsDangerous: u32 (ptr);
SHLWAPI$SHOpenRegStreamA: ptr (ptr, cstr, cstr, u32);
SHLWAPI$SHOpenRegStreamW: ptr (ptr, ptr, ptr, u32);
SHLWAPI$SHOpenRegStream2A: ptr (ptr, cstr, cstr, u32);
SHLWAPI$SHOpenRegStream2W: ptr (ptr, ptr, ptr, u32);
SHLWAPI$SHAllocShared: ptr (ptr, u32, u32);
SHLWAPI$SHFreeShared: u32 (ptr, u32);
SHLWAPI$SHLockShared: ptr (ptr, u32);
SHLWAPI$SHUnlockShared: u32 (ptr);
SHLWAPI$SHIsLowMemoryMachine: u32 (u32);
SHLWAPI$GetMenuPosFromId: i32 (ptr, u32);
SHLWAPI$SHSkipJunction: u32 (ptr, ptr);
SHLWAPI$SHCreateThread: u32 (ptr, ptr, u32, ptr);
SHLWAPI$SHCreateShellPalette: ptr (ptr);
SHLWAPI$ColorRGBToHLS: void (u32, ptr, ptr, ptr);
SHLWAPI$ColorHLSToRGB: u32 (u16, u16, u16);
SHLWAPI$ColorAdjustLuma: u32 (u32, i32, u32);
SHLWAPI$IsInternetESCEnabled: u32 ();
SHLWAPI$SHCreateMemStream: ptr (ptr, u32);

#endif /* BUILTINS_SHLWAPI_H */
